In [302]:
import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score
import xgboost as xgb
from sklearn.model_selection import GridSearchCV

In [303]:
df = pd.read_csv(r"D:\ML_assignment\Australian Vehicle Prices.csv")

In [304]:
df.head()

,Brand,Year,Model,Car/Suv,Title,UsedOrNew,Transmission,Engine,DriveType,FuelType,FuelConsumption,Kilometres,ColourExtInt,Location,CylindersinEngine,BodyType,Doors,Seats,Price
0,Ssangyong,2022.0,Rexton,Sutherland Isuzu Ute,2022 Ssangyong Rexton Ultimate (awd),DEMO,Automatic,"4 cyl, 2.2 L",AWD,Diesel,8.7 L / 100 km,5595,White / Black,"Caringbah, NSW",4 cyl,SUV,4 Doors,7 Seats,51990
1,MG,2022.0,MG3,Hatchback,2022 MG MG3 Auto Excite (with Navigation),USED,Automatic,"4 cyl, 1.5 L",Front,Premium,6.7 L / 100 km,16,Black / Black,"Brookvale, NSW",4 cyl,Hatchback,5 Doors,5 Seats,19990
2,BMW,2022.0,430I,Coupe,2022 BMW 430I M Sport,USED,Automatic,"4 cyl, 2 L",Rear,Premium,6.6 L / 100 km,8472,Grey / White,"Sylvania, NSW",4 cyl,Coupe,2 Doors,4 Seats,108988
3,Mercedes-Benz,2011.0,E500,Coupe,2011 Mercedes-Benz E500 Elegance,USED,Automatic,"8 cyl, 5.5 L",Rear,Premium,11 L / 100 km,136517,White / Brown,"Mount Druitt, NSW",8 cyl,Coupe,2 Doors,4 Seats,32990
4,Renault,2022.0,Arkana,SUV,2022 Renault Arkana Intens,USED,Automatic,"4 cyl, 1.3 L",Front,Unleaded,6 L / 100 km,1035,Grey / Black,"Castle Hill, NSW",4 cyl,SUV,4 Doors,5 Seats,34990

In [305]:
for x in df.columns:
    print(x)
    print(df[x].unique())
    print("*"*39)

Brand
['Ssangyong' 'MG' 'BMW' 'Mercedes-Benz' 'Renault' 'Toyota' 'Land' 'Nissan'
 'Honda' 'Volkswagen' 'Mitsubishi' 'Ford' 'Subaru' 'Hyundai' 'Jeep'
 'Volvo' 'Mazda' 'Abarth' 'Holden' 'Audi' 'Kia' 'Mini' 'Peugeot' 'Suzuki'
 'Dodge' 'Porsche' 'Daihatsu' 'Isuzu' 'Lexus' 'Jaguar' 'Rolls-Royce'
 'Skoda' 'Fiat' 'Haval' 'Citroen' 'LDV' 'HSV' 'Foton' 'Mahindra'
 'Maserati' 'Alfa' 'GWM' 'Ram' 'Tesla' 'Genesis' 'Chrysler' 'Great' 'Opel'
 'Saab' 'Bentley' 'Rover' nan 'Ferrari' 'Cupra' 'Chevrolet' 'Lamborghini'
 'FPV' 'McLaren' 'Chery' 'Iveco' 'Hummer' 'Infiniti' 'BYD' 'Tata' 'Aston'
 'Daewoo' 'Proton' 'Geely' 'Smart' 'Ineos' 'Caterham' 'Hino'
 'International' 'Lotus' 'Polestar' 'Datsun' 'Packard']
***************************************
Year
[2022. 2011. 2004. 2017. 2000. 2013. 2014. 2009. 2018. 2015. 2016. 2012.
 2023. 2005. 2019. 2021. 2007. 2010. 2003. 2008. 2006. 2020. 1999. 2002.
 1995. 1997. 1993. 2001. 1998. 1985. 1992.   nan 1986. 1996. 1994. 1989.
 1990. 1981. 1991. 1959. 1970. 1984. 1975. 1979. 1978. 1940.]
***************************************
Model
['Rexton' 'MG3' '430I' 'E500' 'Arkana' 'Estima' 'Rover' 'Pulsar' '86'
 'Jazz' 'HiAce' 'City' 'Golf' 'X3' 'Outlander' '118D' 'Fiesta' 'Amarok'
 'Outback' 'Mirage' 'Camry' '3' 'I45' 'Territory' 'Qashqai' 'T-Cross'
 'Tucson' 'Focus' 'X-Trail' 'Corolla' 'Yaris' 'Grand' 'Patriot' 'S60'
 'Triton' 'E250' 'A250' 'CX-5' 'Falcon' '595' 'CR-V' 'I30' '6' 'Kluger'
 'Santa' 'Cascada' 'ML320' 'Lancer' 'A5' 'RIO' 'Cherokee' 'Tiguan' 'ASX'
 '220I' 'Imax' 'XV' 'Cooper' '308' 'Commodore' 'I20' 'BT-50' 'Vezel'
 'CX-7' 'Renegade' 'Elgrand' 'Impreza' 'X4' '118I' 'C-CLASS' 'Q7'
 'Celerio' 'Liberty' 'C-HR' 'Forester' 'CX-3' 'Cruze' 'RAV4' 'CLC200'
 'Journey' 'Caddy' 'Civic' 'Compass' 'CX-9' 'Ranger' 'Captiva' '2' 'M135I'
 '330I' 'Q3' 'Accent' 'B-Class' 'Sportage' 'Cayenne' 'Cayman' 'Swift'
 'Navara' 'Hijet' 'Hilux' 'Venue' 'X1' 'Veloster' 'M4' 'Transit' 'Trax'
 'Cerato' 'RS3' 'C200' 'D-MAX' 'A200' 'Puma' 'Sorento' 'MU-X' 'IS350'
 'Stinger' 'Landcruiser' 'A3' 'Trafic' '208' 'HR-V' 'A4' 'Accord' 'SQ5'
 'CLK-Class' 'IS300' 'XF' 'Polo' 'ZS' 'M140I' 'Calais' 'Pajero' 'Q2'
 '218I' 'Patrol' 'Passat' 'Megane' 'Ghost' 'Crafter' 'Tarago' 'Iload'
 'Rodeo' '320D' 'Astra' 'Colorado' 'Octavia' 'UX200' 'Rapid' 'Picanto'
 'Carnival' 'ZST' '500' 'GLA250' 'H9' 'Q5' 'V60' 'Stonic' 'RX300' 'Land'
 'Vitara' 'Clubman' 'C4' '2008' 'Acadia' 'Barina' 'C220' 'C250' 'Alphard'
 'Mustang' 'Elantra' 'Macan' 'Kona' 'Xc' 'X5' 'Pathfinder' 'E2000' 'C43'
 '320I' 'S3' 'M5' 'Glb' 'WRX' 'Dualis' 'RX350' 'IX35' 'Viva' 'Stagea'
 'GLC43' 'Commander' '190' 'Almera' 'Noah' 'C30' 'Multivan' 'Kuga' 'R8'
 'GR' 'Koleos' 'G10' 'Ractis' 'Touareg' 'Escape' 'IS250C' 'Ioniq' '4'
 'S-Class' '116I' 'GLC300' 'SQ7' 'Eclipse' 'Mondeo' 'RX350L' 'Clubsport'
 'Hiace' 'Aurion' 'T60' 'Transporter' 'Celica' 'Tunland' 'PIK-UP' '420I'
 'Kamiq' 'M-Class' 'RX450H' 'Serena' 'GTS' 'AMG' 'CLA250' 'Ghibli' 'Fabia'
 'Romeo' 'Voxy' 'Optima' '328I' 'Caravan' 'SP23' 'XC60' 'Z4' 'Tank' 'M2'
 'A7' 'A1' 'F-Pace' 'ML350' 'Juke' 'Echo' 'C63' 'X6' '1500' 'Skyline'
 'C300' 'Model' 'GLE63' 'Sonata' 'Axela' 'B180' 'Statesman' 'Altima'
 'Superb' 'Alto' 'LS460' 'T-ROC' 'I40' 'ORA' '225I' 'Everest' 'Kangoo' '5'
 'CLA45' 'ES250' 'Note' 'A45' 'E200' 'Sprinter' 'RX450HL' 'A6' 'UTE'
 '330D' 'Caprice' 'V40' 'GV80' 'Niro' 'Staria' 'BRZ' 'Odyssey' 'FJ'
 'Countryman' 'ES350' '300' '3D' 'Wrangler' 'Rav' 'Ducato' 'NX300H'
 'GS450H' 'Baleno' '508' 'Ignis' 'NX300' '3008' 'V80' 'Delica' 'I8'
 'CLS250' 'XC90' 'GLA45' 'RCZ' 'CLA' 'M240I' 'HS' 'GLC' 'Wall' '380'
 'Ecosport' 'RS4' 'GLE' 'M340I' 'MPV' 'Prius' 'Haval' 'Taycan' 'ML63'
 'Combo' 'RS' 'GLA35' 'Sebring' 'GT40' '428I' 'Sai' 'Granvia' 'M235I' '1'
 'E350' 'Rondo' 'Challenger' 'Karoq' 'Other' 'B200' 'Convertible'
 'Fortuner' 'A-CLASS' '435I' 'S5' '230I' 'Maxima' 'E55' 'DS3' 'TT' 'E400'
 'DS4' 'Legacy' 'EOS' 'Captur' 'GLC250' 'Arteon' 'Getz' 'Fit' 'MX-5'
 'Kodiaq' 'A8' '320CI' 'Grancabrio' 'S40' 'Festiva' 'Express' 'CX-30'
 'NX250' 'S4' 'Jetta' '3-Sep' 'E-CLASS' 'Every' '4008' 'Altezza' 'RS6'
 'CT' 'Mulsanne' 'Mini' 'Crown' nan 'Trailblazer' 'Freemont' 'F' 'IS300H'
 'Panda' 'Gladiator' 'ML400' 'B2500' '500X' 'CLS53' 'Micra' 'Clio' '360'
 'NX' 'Scirocco' 'GLA180' 'G10+' 'Formentor' 'XC40' 'ES300H' 'XE' 'X2'
 'Gtsr' 'NX200T' 'Silverado' 'IX' 'GV70' 'Levante' 'Carry' 'Urus' 'SX4'
 'RX' 'X7' 'S450' 'ML250' 'Quattroporte' 'NX350H' 'Viano' 'Deliver' 'Cube'
 'G-Class' '323' '218D' '135I' 'F6' 'IS250' 'Xjsc' 'Endura' 'Leaf' 'A180'
 'CLK320' 'M3' 'Monaro' 'MX-30' 'GLE350' '720S' 'Continental' 'Crewman'
 'GL500' 'Seltos' 'E-Pace' 'Ateca' 'S350' 'CX-8' 'RS5' 'Crosstrek' 'GLC63'
 'Fairmont' '540C' 'Coupe' 'Fairlane' 'Vellfire' 'GLC200' 'Mifa' 'F-Type'
 'CLA200' 'J3' 'LX570' 'G63' 'LC500' 'Master' 'Levorg' 'Scala' '911' 'E63'
 'S65' 'Palisade' 'Jimny' 'Boxster' 'GLE400' 'XL-7' 'Q8' '650S' 'Sambar'
 'F250' 'Expert' 'M8' 'X' 'LX500D' '128TI' '740I' 'V250' 'Nitro' 'RC350'
 'SL55' 'E-Tron' 'RX-8' 'Tribeca' '370Z' 'Equinox' '7' 'Jackaroo' 'R300'
 '220D' 'RX270' 'GT-R' 'Laguna' 'Airtrek' 'X250' 'Mark' 'Murano' '125I'
 'Corvette' 'Tiida' 'F430' 'Avensis' 'Panamera' 'Valente' 'SLC' 'EQA'
 'GLE300' 'XUV500' 'S-Cross' '228I' 'GLA' 'MB100' 'Vito' 'D90' 'RX330'
 'Tribute' 'Musso' '718' 'Roadster' 'Magna' 'A190' 'Caravelle' 'RC200T'
 'E300' 'E240' 'RC' 'Integra' 'Z' 'Jolion' 'GTC4' 'Granturismo' 'Terracan'
 'Daily' 'M6' 'Courier' 'Steed' 'S63' 'Roomster' '318I' 'C180' 'SQ2'
 'Korando' '5008' 'F450' 'E220' 'Kizashi' 'GLC220' 'GLC350' 'Pursuit'
 'RX500H' 'V' 'Marco' 'C5' 'Tundra' 'C3' 'G350' 'CLS500' 'Beetle'
 'Senator' 'Stavic' 'I4' 'H6' 'V240' 'Colt' 'Trajet' 'C230' '307' 'Doblo'
 '335I' '695' '300C' 'H8' 'Adventra' 'LX600' 'S450L' '330CI' 'CR-Z' '323I'
 'Cabrio' 'IS200T' 'CLK63' 'CT200H' 'Berlingo' 'Omoda5' 'Supra' 'H2'
 'CLS350' 'R-Class' 'California' 'GLS350' 'Vectra' 'Genesis' 'ES300'
 'GL63' 'G70' 'Ute' 'GLS500' 'K2700' 'SC430' 'Q50' 'Paceman' 'GLA200'
 'Avalon' 'Atto' '520D' 'Corsa' 'EQB' 'XUV700' 'G80' '340I' 'Spectra'
 'A35' 'GS350' 'GLE450' 'GLA220' 'GLS' 'B250' 'EQS53' 'UX' 'Atlas' 'EQC'
 'Actyon' 'C350' 'Malibu' 'Maloo' 'XKR' 'XC70' 'GL320' 'CLK500' '407'
 'Soul' '570S' 'Aventador' 'Viper' 'XJ8' '207' '530I' 'CC' '612' '120D'
 'E53' 'EV6' '740LI' 'NX350' 'Caldina' 'Arnage' 'Q60' 'Flying' '525I'
 '420D' 'ML500' 'FPV' '121' 'Maybach' 'LX470' 'Maverick' 'Berlina' 'Xenon'
 'MG6' 'XJ' 'SL350' 'APV' 'Martin' 'GLB' '730D' 'CLA35' 'X350' 'I-Pace'
 '5D' 'Lanos' 'Regius' '2500' '120I' 'Verada' 'X200' 'R320' 'Avalanche'
 'GLE250' 'PT' 'J11' 'CLK280' '316I' 'C40' 'Laser' 'GS250' 'LX450D'
 'Prius-C' 'Coaster' 'ML300' 'Grange' 'S16' 'Scudo' 'Kadjar'
 'Cooper_Countryman' '530D' '350Z' 'GS' '325I' 'Century' 'I3' 'MK' 'GR86'
 'GLE43' 'Punto' 'SQ8' 'V50' 'Fortwo' 'Epica' 'GT' 'Mazda3' 'T3'
 'Grenadier' 'Mazda2' 'Seven' 'FTS' 'NLS' 'Stralis' 'Prostar' 'FYJ' 'FSR'
 'CX-90' 'NNR' 'NLR' '700' 'NMR' 'Edeliver' 'Alpina' 'Evora' '600LT'
 'Eurocargo' 'GV60' 'GLE53' 'ZR-V' 'LS500H' '8' '812' 'FVD' 'FYX' 'Trucks'
 'C320' 'FVL' 'NQR' 'Elise' 'FRD' 'Sx4' '520I' 'NPR' 'Aumark' '530E'
 'CX-60' '250' 'FRR' 'M440I' '560' 'LS500' 'Born' 'GL-Class' 'Spark'
 'A170' 'Midget' 'SL500' '300ZX' 'Sierra' 'HDT' '2002' '180' 'Silvia' 'Mr'
 'Leon' 'Stanza' 'CX30' 'SLK350' 'NV350' 'Fuso' 'S430' '420' 'B4000'
 'Scorpio-N' 'E20' '120']
***************************************
Car/Suv
['Sutherland Isuzu Ute' 'Hatchback' 'Coupe' 'SUV' 'ON FOUR WHEELS'
 'Carbarn' 'Commercial' 'USED Dealer ad' 'Exclusive Autohaus'
 'Alto Volkswagen New Cars' 'Sedan' 'NEW In stock' 'Mr Car'
 'Nippon Motors' 'Ute / Tray' 'People Mover' 'Convertible' 'Wagon'
 'Top Auto Group' 'Sydney City Traders' 'Automobile Gallery' 'CBP Motors'
 'Alto Volkswagen Used Cars' '02 **** ****\n' 'Alto Blacktown MG'
 'Redline Motor Group PTY LTD' 'Auto Outlet Direct' 'Global car connect'
 'WHOLESALE MOTOR GROUP' 'RV Motors' 'JR Motors World'
 'Don Frost Car Sales' 'Cumberland Ford' 'Mega Fleet Sales'
 'Western City Autos - Car City Minchinbury' 'Windsor Toyota Used'
 'Carsell Pty Ltd' 'Best Buy Autos Prestige' 'Kingz Motors'
 'Prime Wheels.' 'Sutherland Mazda Used Cars' 'Japan Auto Trading'
 'Vega Motors' 'DEMO' 'National Vehicles' 'Remy Car Company'
 'McMoore Motor Co' 'Bodyfit Autos' 'Awsum Autos - Car City Minchinbury'
 'Melbourne Automobiles Pty Ltd' 'Autoproject' 'Alto Isuzu Ute New Cars'
 '03 **** ****\n' 'Dominelli GWM' 'Audi Alto Artarmon New Cars'
 'Brighton BMW' 'Smile Quality Cars - Car City Minchinbury'
 'Rockdale Mazda New' 'Parramatta Motor Group (Thomson Ford) - Used'
 'Starline Autos' 'Sydney City Volkswagen New'
 'Hot Spot Autos Granville Commercial and 4x4' 'My Car Choice'
 'The Auto House' 'Lander Toyota Used Cars'
 'Adelaide Vehicle Centre Commercial' "Nick's Motors"
 'Adelaide Vehicle Centre - Clearance Centre' 'Southside Auto Wholesale'
 'Sun Auto Group Five Dock' 'City Car Gallery Pty Ltd (Bankstown)'
 'Adelaide Vehicle Centre West' 'Dominelli Ford' 'Chatswood Toyota'
 'Wheelz and Wheelz' 'Alto Skoda Artarmon New Cars' 'Castle Hill Renault'
 'Purely commercials Bibra Lake' 'Webb Auto Sales'
 'Motoring Group Plus Pty Ltd' 'Sunshine Autos'
 'AUS Vehicle Sales - Bassendean' 'Gregg Watts Used Cars (CCM)'
 'Titan Ford' 'Macarthur Renault' '08 **** ****\n'
 'Osborne Park Mazda used' 'Other' 'Hills Motor Group'
 'Porsche Centre Perth used' 'Prestige Motor Gallery'
 'Xtreme Car Sales Administration Pty Ltd' 'Sadek - Elderslie'
 'Australian Motor Traders' 'Edward Lees Imports'
 'Liverpool Volkswagen New Cars' 'Audi Centre Sydney Pre-Owned'
 'Bayford Volkswagen Fairfield' 'Stanmore Mazda'
 'Phillips & Co Automotive' 'Autonomos Wyndham' 'OC Automotive'
 'Mini Garage Sydney - Used Cars' 'Fergusons Toyota South Hurstville'
 'CarNet Smithfield' 'Saap Auto' 'Sydney Luxury Motors'
 'Washington Partners Prestige' 'Sydney City Skoda' 'Peter Warren Toyota'
 'Macarthur Suzuki' 'Triple F Autos Pty Ltd'
 'Alto Volkswagen North Shore New Cars' nan
 'Suttons Mitsubishi Arncliffe- New/Demo'
 'Heritage Auto Group - AL Berwick Pty Ltd'
 'Pennant Hills Auto Traders - Used' 'Motor One Garage'
 'Volvo Cars Liverpool' 'Alto North Shore MG' 'Sydney City Lexus'
 'Cosmopolitan Cars - NSW' 'Sydney City Volkswagen Commercial'
 'Peter Warren Jeep' 'Sutherland Volkswagen New Cars'
 'Suttons Nissan Chullora- New/Demo'
 "Berwick Mitsubishi - Melbourne's Used Car Destination" 'VersionOne Auto'
 'Luxe Autohaus' 'Carmart.com.au' 'Suttons Nissan Arncliffe- New/Demo'
 'Auto Dynasty Cars' 'Sutherland Mazda New Cars'
 'Lorbek Luxury Cars Sydney' 'Suttons GWM Haval Chullora- New/Demo'
 'Adelaide Vehicle Centre South' 'Sylvania BMW Used Cars'
 'Suttons Ford Chullora- New/Demo'
 'Greg Watts Motors - Car City Minchinbury' 'Timmy Car Co Pty Ltd'
 'Sydney City Volkswagen Pre Owned' 'Macarthur Jaguar'
 'Col Crawford Renault New & Demo'
 "Wholesale House Brissy's Best Used 4x4 and Commercials"
 'Hot Spot Autos Granville' 'Suttons Hyundai Arncliffe- New/Demo'
 'Audi Alto MacArthur Used Cars' 'Mornington Mazda'
 'Continental Cars Citroen Centre' 'Sylvania BMW Demo' 'Vehicle Masters'
 'Liverpool Mazda New Cars' 'Albion Park Motor Group'
 'Harrigan Motor Group Used - Illawarra' 'Carma' 'Highlands Garage'
 'Newcastles Cheapest Cars Used' 'Adelaide Vehicle Centre Hills'
 'Tony Lahood Motors Croydon' 'Cars from Japan'
 'Adelaide Vehicle Centre North' 'Blue Mountains Mazda'
 'Hove Car Sales Pty Ltd' 'Southern Classic Cars - New & Demo'
 'Wollongong Mazda' 'Fusion Auto Sales'
 'Southern Classic Cars Albion Park' 'Peter Warren Ford'
 'Motor Vehicle Wholesale Dot Com' 'Big Rock Toyota used'
 'Capital Automotive group' 'SJ Wholesale Motors'
 'Australian Car Sales Group - Car City Minchinbury'
 'Southside Volkswagen used' 'Seymours on Tudor'
 'Newcastle Vehicle Exchange' 'Peter Warren Renault'
 'Hunter Valley Motor Group' 'Lancaster Automotive Holdings New Cars'
 'Rockdale Mazda' 'Bathurst Volkswagen' 'Sutherland Isuzu Ute - New'
 'Macarthur Jeep' 'Liverpool Mazda Used Cars' 'Orange Toyota (Used)'
 'Upper Hunter Automotive New Cars' 'Commercial Buys Pty Ltd'
 'Central Coast Automotive Gosford' 'Clancy Motors Used Cars'
 'Kloster BMW and MINI Garage - used'
 'McGrath Mitsubishi Liverpool New Cars' 'Col Crawford Hyundai'
 'Canberra Toyota Phillip' 'Valley Motor Auctions'
 'Capital Honda Used Cars' 'Port Stephens Toyota' 'Lennock Hyundai'
 '4B4 Warehouse' 'Autohome Australia' 'Lennock Motors'
 'Oldtimer Centre Pty Ltd' 'National Capital Motors New Cars'
 'Mercedes-Benz Peter Warren' 'Taree City Car Sales'
 'Manning Valley Automotive' 'Illawarra Used Cars Albion Park'
 'McGuinness Motors' 'Coffs Harbour Toyota Pre-Owned'
 'Bellbowrie Motor Group New Cars' 'Manning Valley Automotive - New Cars'
 'Wangaratta Motor Group Used' 'McGrath Subaru Liverpool New Cars'
 'Miedecke Motor Group - New' 'SGM 4x4 & Commercials (Macksville)'
 'Top Used Cars' 'Jacob Toyota' 'Wodonga Prestige Volkswagen'
 'Valley Motor Group New' 'Valley Ford Traralgon New'
 'Newcastle Skoda New' 'Gulson Canberra - New & Demo' 'Maitland Toyota'
 'Lexus of Southport' 'Automotion Used Cars - Sale' 'Valley Cars'
 'Garage Apex Epping' 'UniBee Australia'
 'National Capital Hyundai, National Capital Mitsubishi' 'CARS 4 YOU'
 'Melbourne Truck and Vans' 'Stevron Autos' 'Miedecke Motor Group - Used'
 'Kinghorn Pre-Owned' 'Knox Ford & Jeep' 'Blacklocks Lavington - Used'
 'Audi Centre Gold Coast NEW Frizelle Sunshine Automotive'
 'Fueled up Garage' 'Cardiff Volkswagen New' 'Market City Motors'
 'Berwick Toyota' 'Barry Bourke GMSV, Suzuki, Renault & LDV New'
 'Burwood Nissan New' 'Robina USED Frizelle Sunshine Automotive'
 'Ferntree Gully Automotive' 'Auto Mega Warehouse Dandenong' 'Alphamotive'
 'CONCORD CAR SALES' 'Max Ouzas Prestige Cars' 'Berwick Nissan Used Cars'
 'Central Star Autohaus- Waverley' 'Simple Cars' 'Doncaster Volkswagen'
 'Traralgon Car City' 'Southport Car Sales'
 'Mantello LDV & Suzuki New Cars'
 'Renault NEW Frizelle Sunshine Automotive' 'Valley Ford Traralgon Used'
 'Pakenham Toyota' 'Sunshine Volvo NEW Frizelle Sunshine Automotive'
 "Tim's Highway Cars - Car City Ringwood" 'Auto Mega Warehouse Fairfield'
 'South East Commercials' 'PETER LENNOX AUTOMOTIVE'
 'Gold Coast Wholesale Cars' 'Cars Of Melbourne' 'Innes Motors Used Cars'
 'East Coast Commercials Gold Coast' 'Ringwood Nissan and MG New & Demo'
 'Hyon Motors'
 'Gold Coast Volkswagen Commercial Centre NEW Frizelle Sunshine Automotive'
 'The Car Place' 'Rap Car Sales - Car City Ringwood'
 'Penfold Motor Group used' 'Lexus of Berwick' 'Doncaster Hyundai - NEW'
 'Ferntree Gully Hyundai & Kia Used Cars' 'Ferntree Gully Kia (New)'
 'Hallam Used Cars' "Ralph D'Silva Suzuki" 'East motors'
 'Von Bibra Group Robina USED' 'Seconds Garage' 'Eastern Subaru'
 'Melbourne City Toyota Heidelberg' 'Frankston Renault and Isuzu'
 'Cheapest Carsales' "Ralph D'Silva Mitsubishi" 'M1 Used Cars'
 'Melbourne Quality Cars' 'Motorman Imports' 'Springwood GWM HAVAL'
 'Redlands Mazda Used' 'The Cheap Car Co Pty Ltd'
 'Consign-A-Car P/L (Kedron)' 'Auto Mega Warehouse Brisbane'
 'Automotive Consultants' 'Kedron Haval & Great Wall Online'
 'Jeff Wignall Ford - Frankston'
 'Gold Coast Chrysler Jeep Dodge NEW Frizelle Sunshine Automotive'
 'Bay City Holden Used.' 'Toowoomba Mahindra'
 'East Coast Commercials - Used' 'Oldmac MG New'
 'Westpoint Haval, GWM, Mahindra, SsangYong' 'Dream Automotive QLD'
 'Hillcrest GWM HAVAL' '07 **** ****\n' "LV's Discount Cars"
 'MP AUTOS PTY LTD' "Melbourne's Cheapest Cars"
 'Toowoomba Automotive Used Cars' 'Werribee Hyundai'
 'Unique Cars and Finance' 'Mount Gravatt Mazda New'
 'Brisbane Auto Group (BAG)' 'Blue Ribbon Motors'
 'Premium Cars Queensland' 'Cars4us' 'Altous Motors'
 'Wheelchair Vehicle Sales' 'Lorbek Luxury Cars Melbourne'
 "Ralph D'Silva Hyundai" 'Blackburn Nissan Used'
 'Patterson Cheney Toyota Used Cars' 'The car warehouse oakleigh'
 'Robina Volkswagen NEW Frizelle Sunshine Automotive' 'Brighton MG'
 'Melbourne City Toyota' 'Sci-Fleet Indooroopilly' 'Mornington Toyota'
 'Q Suzuki - New' 'Cricks Highway New & Demo' 'Werribee Mitsubishi New'
 'Brighton Mazda New & Demo' 'Wippells Autos' 'City Jeep New Cars'
 'City Jeep - Pre Owned' 'JDMHQ' 'The Car Finance Factory'
 'Hollywood Motors' 'LEXUS OF TOOWOOMBA' 'Cranbourne Toyota' 'Blinkr'
 'Ipswich Mazda' "Tony's Car Sales"
 'Brisbane City Used Cars T/U: Toowong Automotive'
 'Norris Motor Group Volkswagen' 'Automobex Pty Ltd' 'Brisbane Car Yard'
 "Tradie's Heaven" 'Springwood MG - New' 'Cheapest Cars Melbourne'
 'Werribee Jeep' 'AUDI MORNINGTON' "Brisbane's Cheaper Cars"
 'Westpoint Autos Hyundai New Cars' 'Bay City HSV & Suzuki'
 'BRIGHTON CHRYSLER JEEP USED CARS' 'Hillcrest Hyundai New Cars'
 'Wacol Wholesale Cars' 'Moreton Bay Suzuki - New' 'Brighton Ssangyong'
 'Motorama Mitsubishi Moorooka Used' 'Coast 2 Coast Vehicles Pty Ltd'
 'Fortis Motor Group' 'Mornington Hyundai & MG Used Cars'
 'Browns Plains MG New' 'Caroline Springs Jeep New' 'Gas Sports Cars'
 'First Choice Motors' 'Westpoint Autos Nissan & Suzuki New Cars'
 'Brighton Renault, Suzuki & Nissan New' 'Redland Mazda New'
 'Auto Mega Warehouse Westgate' 'Simply Automotive' 'Chadstone Toyota'
 'Bremer Suzuki - New' 'IPSWICH VOLKSWAGEN' 'Lexus of Indooroopilly'
 'Kedron Car Centre' 'AUDI CENTRE MELBOURNE' 'Alpha Car Group'
 'Ideal Cars Automotive' 'Bedggoods - Used & Demos' 'Mornington Nissan'
 'Blood Toyota' '4x4 Mega Centre' 'Caboolture City Autos'
 'Rex Gorell New Cars' 'Hillcrest Suzuki New Cars' 'Geelong BMW New'
 'Qld 4x4 Pty Ltd' 'Special Vehicle Imports' 'Autopoint'
 'Kunda Park Used Cars' 'Sunshine Coast Mazda New and Demonstrator'
 'Noosa Auto Group Mazda New Car' 'Pacific Great Wall Haval Caloundra New'
 'Western Highway Honda' 'Pacific Gympie' 'Brighton Mitsubishi New'
 'Noosa Village Autos' 'Car Mate Warehouse Ballarat'
 'Springwood Nissan New' 'GK Car Sales' 'Rex Gorell Nissan New'
 'Centenary Motors' 'Sunbury Ford' 'Pacific Isuzu Used Cars'
 'Coastal Car Talk' 'Noosa GWM' 'Zoopers Devonport'
 'Fraser Coast Motor Centre Suzuki' 'Carlin and Gazzard'
 'Melbourne Car Center' 'The Consignment Centre'
 'Jackson Motor Company Hobart City' 'Powell Motor Group New & Demo'
 'Tilford Auto Group Used' 'Newspot Suzuki Salisbury Park'
 'Newspot MG Hampstead Gardens' 'Central West Motors' 'Newspot Jeep'
 'Hoppers Crossing Motor Garage' 'STEINBORNER BAROSSA'
 'Newspot Suzuki Hampstead Gardens' 'Ipswich Kia' 'Adelaide Hills Toyota'
 'Suzuki In The City - New' 'Offroad Pros Pty Ltd'
 'REX GORELL VOLKSWAGEN GEELONG New' 'Geelong MINI New'
 'Auto Master Car Sales' 'REX GORELL VOLVO New' 'Edwardstown Mazda - New'
 'Wayne Phillis SsangYong' 'Newspot MG Adelaide' 'Southern Vales Nissan'
 'Adelaide BMW' 'Pacific Great Wall Haval Caloundra Used'
 'Pickering Auto Group Mitsubishi New Car' 'Morrow Motor Group'
 'Pickering Auto Group MG New Car'
 'Jackson Motor Company South Launceston' 'Buckby Motors'
 'Pickering Auto Group LDV New Car' 'REX GORELL FORD'
 'Mildura Motor Holdings New/Demos' 'Trinity Earlville New Cars'
 'Pacific Toyota Used' 'A Cullen & Son' 'KQ Autos'
 'Hidden Valley Used Cars' 'Darwin Motor Group MG'
 'Darwin Motor Group Used' 'Auto Trend Winnellie'
 'Duttons Murray Bridge Used Cars' 'First Choice Freo' 'Linemac Motors'
 'Gamers Autos' 'Peter Kittle Toyota' 'Main North Renault'
 'Next Drive Motors' 'Bundaberg Motors Group Jeep Dodge New'
 '3MT True Value Auto' 'Stockman Holden' 'John Hughes Passenger'
 'Newspot MG Salisbury Park' 'Rockingham Toyota' 'Prospect Motor Company'
 'Affordable Motors' 'Reef City Motors - Used Cars' 'STEINBORNER GAWLER'
 'Adelaide City Jeep' 'Wayne Phillis Ford' 'CMI Southside - Used'
 'South Central Motors' 'Adelaide City GWM Haval' 'TAG Volvo New Cars'
 'Sinergy Motorsports' 'Adrian Brien Renault'
 'Pickering Auto Group Hyundai New Car' 'Newspot RAM Salisbury Park'
 'Trinity Earlville Used Cars' 'CRYSTAL CAR CARE & SALES'
 'First In Vehicles' 'Pacific Toyota City Used Cars' 'Freedom Motors'
 'Darwin Motor Group Hyundai' 'Carhub Automotive'
 'CMG Adelaide - Adelaide City Kia, LDV & GMSV' 'Vanswest'

In [306]:
df.isnull().sum()

Brand                   1
Year                    1
Model                   1
Car/Suv                28
Title                   1
UsedOrNew               1
Transmission            1
Engine                  1
DriveType               1
FuelType                1
FuelConsumption         1
Kilometres              1
ColourExtInt            1
Location              450
CylindersinEngine       1
BodyType              282
Doors                1604
Seats                1705
Price                   3
dtype: int64

In [307]:
df.dropna(inplace=True)

In [308]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 14586 entries, 0 to 16733
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Brand              14586 non-null  object
 1   Year               14586 non-null  float64
 2   Model              14586 non-null  object
 3   Car/Suv            14586 non-null  object
 4   Title              14586 non-null  object
 5   UsedOrNew          14586 non-null  object
 6   Transmission       14586 non-null  object
 7   Engine             14586 non-null  object
 8   DriveType          14586 non-null  object
 9   FuelType           14586 non-null  object
 10  FuelConsumption    14586 non-null  object
 11  Kilometres         14586 non-null  object
 12  ColourExtInt       14586 non-null  object
 13  Location           14586 non-null  object
 14  CylindersinEngine  14586 non-null  object
 15  BodyType           14586 non-null  object
 16  Doors              14586 non-null  object
 17  Seats              14586 non-null  object
 18  Price              14586 non-null  object
dtypes: float64(1), object(18)
memory usage: 2.2+ MB

In [309]:
df.drop('ColourExtInt',axis=1,inplace=True)

In [310]:
df.drop('Title',axis=1,inplace=True)

In [311]:
df.head()

,Brand,Year,Model,Car/Suv,UsedOrNew,Transmission,Engine,DriveType,FuelType,FuelConsumption,Kilometres,Location,CylindersinEngine,BodyType,Doors,Seats,Price
0,Ssangyong,2022.0,Rexton,Sutherland Isuzu Ute,DEMO,Automatic,"4 cyl, 2.2 L",AWD,Diesel,8.7 L / 100 km,5595,"Caringbah, NSW",4 cyl,SUV,4 Doors,7 Seats,51990
1,MG,2022.0,MG3,Hatchback,USED,Automatic,"4 cyl, 1.5 L",Front,Premium,6.7 L / 100 km,16,"Brookvale, NSW",4 cyl,Hatchback,5 Doors,5 Seats,19990
2,BMW,2022.0,430I,Coupe,USED,Automatic,"4 cyl, 2 L",Rear,Premium,6.6 L / 100 km,8472,"Sylvania, NSW",4 cyl,Coupe,2 Doors,4 Seats,108988
3,Mercedes-Benz,2011.0,E500,Coupe,USED,Automatic,"8 cyl, 5.5 L",Rear,Premium,11 L / 100 km,136517,"Mount Druitt, NSW",8 cyl,Coupe,2 Doors,4 Seats,32990
4,Renault,2022.0,Arkana,SUV,USED,Automatic,"4 cyl, 1.3 L",Front,Unleaded,6 L / 100 km,1035,"Castle Hill, NSW",4 cyl,SUV,4 Doors,5 Seats,34990

In [312]:
df.head()

,Brand,Year,Model,Car/Suv,UsedOrNew,Transmission,Engine,DriveType,FuelType,FuelConsumption,Kilometres,Location,CylindersinEngine,BodyType,Doors,Seats,Price
0,Ssangyong,2022.0,Rexton,Sutherland Isuzu Ute,DEMO,Automatic,"4 cyl, 2.2 L",AWD,Diesel,8.7 L / 100 km,5595,"Caringbah, NSW",4 cyl,SUV,4 Doors,7 Seats,51990
1,MG,2022.0,MG3,Hatchback,USED,Automatic,"4 cyl, 1.5 L",Front,Premium,6.7 L / 100 km,16,"Brookvale, NSW",4 cyl,Hatchback,5 Doors,5 Seats,19990
2,BMW,2022.0,430I,Coupe,USED,Automatic,"4 cyl, 2 L",Rear,Premium,6.6 L / 100 km,8472,"Sylvania, NSW",4 cyl,Coupe,2 Doors,4 Seats,108988
3,Mercedes-Benz,2011.0,E500,Coupe,USED,Automatic,"8 cyl, 5.5 L",Rear,Premium,11 L / 100 km,136517,"Mount Druitt, NSW",8 cyl,Coupe,2 Doors,4 Seats,32990
4,Renault,2022.0,Arkana,SUV,USED,Automatic,"4 cyl, 1.3 L",Front,Unleaded,6 L / 100 km,1035,"Castle Hill, NSW",4 cyl,SUV,4 Doors,5 Seats,34990

In [313]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 14586 entries, 0 to 16733
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Brand              14586 non-null  object
 1   Year               14586 non-null  float64
 2   Model              14586 non-null  object
 3   Car/Suv            14586 non-null  object
 4   UsedOrNew          14586 non-null  object
 5   Transmission       14586 non-null  object
 6   Engine             14586 non-null  object
 7   DriveType          14586 non-null  object
 8   FuelType           14586 non-null  object
 9   FuelConsumption    14586 non-null  object
 10  Kilometres         14586 non-null  object
 11  Location           14586 non-null  object
 12  CylindersinEngine  14586 non-null  object
 13  BodyType           14586 non-null  object
 14  Doors              14586 non-null  object
 15  Seats              14586 non-null  object
 16  Price              14586 non-null  object
dtypes: float64(1), object(16)
memory usage: 2.0+ MB

In [314]:
import regex

In [315]:
# Use str.replace to remove the non-numeric characters
df['Doors'] = df['Doors'].str.replace(r'[^0-9]', '', regex=True)
df['Seats'] = df['Seats'].str.replace(r'[^0-9]', '', regex=True)
df['CylindersinEngine'] = df['CylindersinEngine'].str.replace(r'[^0-9]', '', regex=True)

In [316]:
df['Doors']=pd.to_numeric(df['Doors'],errors='coerce')
df['Seats']=pd.to_numeric(df['Seats'],errors='coerce')
df['CylindersinEngine']=pd.to_numeric(df['CylindersinEngine'],errors='coerce')

In [317]:
df['Price']=pd.to_numeric(df['Price'],errors='coerce')

In [318]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 14586 entries, 0 to 16733
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Brand              14586 non-null  object
 1   Year               14586 non-null  float64
 2   Model              14586 non-null  object
 3   Car/Suv            14586 non-null  object
 4   UsedOrNew          14586 non-null  object
 5   Transmission       14586 non-null  object
 6   Engine             14586 non-null  object
 7   DriveType          14586 non-null  object
 8   FuelType           14586 non-null  object
 9   FuelConsumption    14586 non-null  object
 10  Kilometres         14586 non-null  object
 11  Location           14586 non-null  object
 12  CylindersinEngine  14586 non-null  int64
 13  BodyType           14586 non-null  object
 14  Doors              14586 non-null  int64
 15  Seats              14586 non-null  int64
 16  Price              14551 non-null  float64
dtypes: float64(2), int64(3), object(12)
memory usage: 2.0+ MB

In [319]:
df['Year']=pd.to_numeric(df['Year'],errors='coerce').astype(int)

In [320]:
df.head()

,Brand,Year,Model,Car/Suv,UsedOrNew,Transmission,Engine,DriveType,FuelType,FuelConsumption,Kilometres,Location,CylindersinEngine,BodyType,Doors,Seats,Price
0,Ssangyong,2022,Rexton,Sutherland Isuzu Ute,DEMO,Automatic,"4 cyl, 2.2 L",AWD,Diesel,8.7 L / 100 km,5595,"Caringbah, NSW",4,SUV,4,7,51990.0
1,MG,2022,MG3,Hatchback,USED,Automatic,"4 cyl, 1.5 L",Front,Premium,6.7 L / 100 km,16,"Brookvale, NSW",4,Hatchback,5,5,19990.0
2,BMW,2022,430I,Coupe,USED,Automatic,"4 cyl, 2 L",Rear,Premium,6.6 L / 100 km,8472,"Sylvania, NSW",4,Coupe,2,4,108988.0
3,Mercedes-Benz,2011,E500,Coupe,USED,Automatic,"8 cyl, 5.5 L",Rear,Premium,11 L / 100 km,136517,"Mount Druitt, NSW",8,Coupe,2,4,32990.0
4,Renault,2022,Arkana,SUV,USED,Automatic,"4 cyl, 1.3 L",Front,Unleaded,6 L / 100 km,1035,"Castle Hill, NSW",4,SUV,4,5,34990.0

In [321]:
df.columns

Index(['Brand', 'Year', 'Model', 'Car/Suv', 'UsedOrNew', 'Transmission',
       'Engine', 'DriveType', 'FuelType', 'FuelConsumption', 'Kilometres',
       'Location', 'CylindersinEngine', 'BodyType', 'Doors', 'Seats', 'Price'],
      dtype='object')

In [322]:
df['FuelConsumption'] = df['FuelConsumption'].str.extract(r'([0-9.]+)').astype(float)

In [362]:
df.head()

,Brand,Year,Model,UsedOrNew,Transmission,DriveType,FuelType,FuelConsumption,Kilometres,CylindersinEngine,BodyType,Doors,Seats,Price,cylinders,engine_displacement
0,53,2022,349,0,1,1,1,8.7,5595.0,4,6,4,7,51990.0,4.0,2.2
1,35,2022,268,2,1,2,5,6.7,16.0,4,3,5,5,19990.0,4.0,1.5
3,40,2011,150,2,1,3,5,11.0,136517.0,8,2,2,4,32990.0,8.0,5.5
4,49,2022,61,2,1,2,6,6.0,1035.0,4,6,4,5,34990.0,4.0,1.3
7,43,2000,320,2,1,2,6,8.0,300539.0,4,3,5,5,2995.0,4.0,1.6

In [323]:

# Extract number of cylinders and engine displacement
df['cylinders'] = df['Engine'].str.extract(r'(\d+) cyl').astype(float)
df['engine_displacement'] = df['Engine'].str.extract(r'(\d+\.\d+) L').astype(float)

In [324]:
df.head()

,Brand,Year,Model,Car/Suv,UsedOrNew,Transmission,Engine,DriveType,FuelType,FuelConsumption,Kilometres,Location,CylindersinEngine,BodyType,Doors,Seats,Price,cylinders,engine_displacement
0,Ssangyong,2022,Rexton,Sutherland Isuzu Ute,DEMO,Automatic,"4 cyl, 2.2 L",AWD,Diesel,8.7,5595,"Caringbah, NSW",4,SUV,4,7,51990.0,4.0,2.2
1,MG,2022,MG3,Hatchback,USED,Automatic,"4 cyl, 1.5 L",Front,Premium,6.7,16,"Brookvale, NSW",4,Hatchback,5,5,19990.0,4.0,1.5
2,BMW,2022,430I,Coupe,USED,Automatic,"4 cyl, 2 L",Rear,Premium,6.6,8472,"Sylvania, NSW",4,Coupe,2,4,108988.0,4.0,NaN
3,Mercedes-Benz,2011,E500,Coupe,USED,Automatic,"8 cyl, 5.5 L",Rear,Premium,11.0,136517,"Mount Druitt, NSW",8,Coupe,2,4,32990.0,8.0,5.5
4,Renault,2022,Arkana,SUV,USED,Automatic,"4 cyl, 1.3 L",Front,Unleaded,6.0,1035,"Castle Hill, NSW",4,SUV,4,5,34990.0,4.0,1.3

In [325]:
df.drop('Car/Suv',axis=1,inplace=True)

In [326]:
df.drop('Location',axis=1,inplace=True)

In [327]:
df['Kilometres']=pd.to_numeric(df['Kilometres'],errors='coerce')

In [328]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [329]:
df.drop('Engine',axis=1,inplace=True)

In [330]:
dff=df

In [331]:
cat_val=[]

In [332]:
for i in dff.columns:
    if dff[i].dtype=='object':
        cat_val.append(i)

In [333]:
cat_val

['Brand',
 'Model',
 'UsedOrNew',
 'Transmission',
 'DriveType',
 'FuelType',
 'BodyType']

In [335]:
df.head()

,Brand,Year,Model,UsedOrNew,Transmission,DriveType,FuelType,FuelConsumption,Kilometres,CylindersinEngine,BodyType,Doors,Seats,Price,cylinders,engine_displacement
0,Ssangyong,2022,Rexton,DEMO,Automatic,AWD,Diesel,8.7,5595.0,4,SUV,4,7,51990.0,4.0,2.2
1,MG,2022,MG3,USED,Automatic,Front,Premium,6.7,16.0,4,Hatchback,5,5,19990.0,4.0,1.5
2,BMW,2022,430I,USED,Automatic,Rear,Premium,6.6,8472.0,4,Coupe,2,4,108988.0,4.0,NaN
3,Mercedes-Benz,2011,E500,USED,Automatic,Rear,Premium,11.0,136517.0,8,Coupe,2,4,32990.0,8.0,5.5
4,Renault,2022,Arkana,USED,Automatic,Front,Unleaded,6.0,1035.0,4,SUV,4,5,34990.0,4.0,1.3

In [336]:
df.isnull().sum()

Brand                     0
Year                      0
Model                     0
UsedOrNew                 0
Transmission              0
DriveType                 0
FuelType                  0
FuelConsumption           0
Kilometres              105
CylindersinEngine         0
BodyType                  0
Doors                     0
Seats                     0
Price                    35
cylinders                90
engine_displacement    5666
dtype: int64

In [337]:
df.dropna(inplace=True)

In [338]:
x=df.drop('Price',axis=1)
y=df['Price']

In [339]:
x.isnull().sum()

Brand                  0
Year                   0
Model                  0
UsedOrNew              0
Transmission           0
DriveType              0
FuelType               0
FuelConsumption        0
Kilometres             0
CylindersinEngine      0
BodyType               0
Doors                  0
Seats                  0
cylinders              0
engine_displacement    0
dtype: int64

In [340]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [342]:
import pickle
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

# Features and their encoders
encoders = {
    'Brand': LabelEncoder(),
    'Model': LabelEncoder(),
    'UsedOrNew': LabelEncoder(),
    'Transmission': LabelEncoder(),
    'DriveType': LabelEncoder(),
    'FuelType': LabelEncoder(),
    'BodyType': LabelEncoder()
}
en=OneHotEncoder()
en.fit(df[encoders.keys()])
transformed_data = {}

for feature, encoder in encoders.items():
    
    # transformed_data[feature] = encoder.fit_transform(df[feature])
    df[feature]= encoder.fit_transform(df[feature])
    x_train[feature]=encoder.transform(x_train[feature])
    x_test[feature]=encoder.transform(x_test[feature])
 
    with open(f'{feature}_encoder.pkl', 'wb') as f:
        pickle.dump(encoder, f)

print("All encoders have been fit, transformed, and pickled successfully!")

All encoders have been fit, transformed, and pickled successfully!

In [344]:
from sklearn.preprocessing import LabelEncoder

In [345]:
df.columns

Index(['Brand', 'Year', 'Model', 'UsedOrNew', 'Transmission', 'DriveType',
       'FuelType', 'FuelConsumption', 'Kilometres', 'CylindersinEngine',
       'BodyType', 'Doors', 'Seats', 'Price', 'cylinders',
       'engine_displacement'],
      dtype='object')

In [346]:
cat_val

['Brand',
 'Model',
 'UsedOrNew',
 'Transmission',
 'DriveType',
 'FuelType',
 'BodyType']

In [347]:
x_train.head()

,Brand,Year,Model,UsedOrNew,Transmission,DriveType,FuelType,FuelConsumption,Kilometres,CylindersinEngine,BodyType,Doors,Seats,cylinders,engine_displacement
5150,22,2014,112,2,1,2,6,9.0,166442.0,4,6,4,7,4.0,2.4
9163,38,2018,39,2,1,2,6,7.0,38808.0,4,7,4,5,4.0,2.5
13343,58,2014,317,2,2,2,5,4.9,145393.0,4,3,5,5,4.0,1.2
2750,33,2012,353,2,1,1,1,5.7,218569.0,4,6,5,5,4.0,2.2
10256,23,2016,123,2,1,2,6,6.0,72988.0,4,7,4,5,4.0,1.5

In [348]:
lr_model = LinearRegression()
lr_model.fit(x_train, y_train)
y_pred_lr = lr_model.predict(x_test)

In [349]:
mean_squared_error(y_test, y_pred_lr, squared=False)

14916.910246194937

In [350]:
r2_score(y_test, y_pred_lr)

0.6062850138999252

In [351]:
rf_model = RandomForestRegressor(random_state=42)

In [352]:
rf_model.fit(x_train, y_train)

RandomForestRegressor(random_state=42)

In [353]:
y_pred_rf = rf_model.predict(x_test)

In [354]:
r2_score(y_test, y_pred_rf)

0.859622269751461

In [355]:
xgb_model = xgb.XGBRegressor(random_state=42)
xgb_model.fit(x_train, y_train)
y_pred_xgb = xgb_model.predict(x_test)

In [356]:
r2_score(y_test, y_pred_xgb)

0.9094792551971779

In [357]:
# param_grid = {
#             'n_estimators': [100, 200, 500],
#             'max_depth': [None, 10, 20, 30],
#             'min_samples_split': [2, 5, 10],
#         }
# grid_search = GridSearchCV(estimator=rf_model, param_grid=param_grid, cv=3, scoring='neg_mean_squared_error', verbose=2, n_jobs=-1)
# grid_search.fit(x_train, y_train)
# best_rf_model = grid_search.best_estimator_
# y_pred_tuned_rf = best_rf_model.predict(x_test)

In [358]:
import pickle

In [359]:
feature_names=x_train.columns.tolist()

In [360]:
feature_names

['Brand',
 'Year',
 'Model',
 'UsedOrNew',
 'Transmission',
 'DriveType',
 'FuelType',
 'FuelConsumption',
 'Kilometres',
 'CylindersinEngine',
 'BodyType',
 'Doors',
 'Seats',
 'cylinders',
 'engine_displacement']

In [361]:
with open("Raga.pkl",'wb') as file:
    pickle.dump((xgb_model,feature_names),file)

In [366]:
with open("Pickle.pkl",'wb') as file:
    pickle.dump((rf_model),file)

In [364]:
with open("firse.pkl",'wb') as file:
    pickle.dump((lr_model,feature_names),file)

In [367]:
import gzip

In [368]:
with gzip.open("compressed_Pickle.pkl",'wb') as file:
    pickle.dump((rf_model),file)